// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lckkuylmvuqjivgnpkgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxja2t1eWxtdnVxaml2Z25wa2d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTQ4ODAsImV4cCI6MjA3MzgzMDg4MH0.o6GsWyQkRxxz8Kp00TwmH8Lgw2Hi1zJhCMqo2WZgbgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});